services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgrest
    networks:
      - widgets-net

  postgrest:
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/postgres
      PGRST_DB_SCHEMA: widgets
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_POOL: 400
      #PGRST_SERVER_TIMING_ENABLED: true #provides timing info for each request in the response header.
    deploy:
      replicas: 10 #
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    networks:
      - widgets-net

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - widgets-net
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "max_connections=4000"
    deploy:
      resources:
        limits:
          memory: 4GB
        reservations:
          memory: 2GB
  
  go-loader:
    build: ./go-loader
    environment:
      MAX_WORKERS: 10
      NGINX_URL: http://nginx:80
    deploy:
      replicas: ${GO_LOADER_REPLICAS:-0}
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    networks:
      - widgets-net


### Below is an image i used to test the integaration before defaulting to go for speed.
  # python-loader:
  #   build: ./python-loader
  #   command: python /app/loader.py
  #   volumes:
  #     - ./python-loader:/app
  #   environment:
  #     PING__INTERVAL: 0.2
  #   depends_on:
  #     - postgrest
  #     - victoria
  #   networks:
  #     - widgets-net
  #   deploy:
  #     replicas: 0
  #     resources:
  #       limits:
  #         cpus: '0.2'
  #         memory: 128M
  #       reservations:
  #         cpus: '0.05'
  #         memory: 64M

  victoria:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    volumes:
      - ./victoria-metrics-data:/victoria-metrics-data
    networks:
      - widgets-net

volumes:
  victoria-metrics-data:

networks:
  widgets-net:
    driver: bridge